<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_togglePassword</name>
   <tag></tag>
   <elementGuidId>a2fce1ad-9057-43e3-9a75-51dae8c2ff08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#togglePassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='togglePassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show Password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8820405-0acd-451e-a72b-939c090aa82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e0ed096c-2e99-408e-a0d9-5b32b82f0776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>togglePassword</value>
      <webElementGuid>b10d764e-3278-404e-ad04-6d0daf7ed6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;togglePassword&quot;)</value>
      <webElementGuid>3b81fb13-7d59-4ed3-9dc0-61d3ed8d24d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='togglePassword']</value>
      <webElementGuid>d6bb7da3-93ce-4f02-8f8e-d0b8a7a18bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/input</value>
      <webElementGuid>d3b4ef76-3a8b-4226-bd5d-3ac5fc7657b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>bf9a8398-6d96-4ed2-99a8-c63412e37b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'togglePassword']</value>
      <webElementGuid>8a2c1f66-7da4-4dad-a4df-c141be00012d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
