<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama UMKM_umkm_name</name>
   <tag></tag>
   <elementGuidId>e2d342bc-fb40-4669-8693-86196e14b63e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#umkm_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='umkm_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nama UMKM&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d49eeba-377c-416b-bede-6201014cb4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f33d29f0-5841-4095-8b0d-f49bf1b1ca56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>umkm_name</value>
      <webElementGuid>41b525f8-d2af-46de-9d8c-cb024aae3940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>umkm_name</value>
      <webElementGuid>69336acb-fc8e-4c8a-89ad-a786434b3a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input px-2 py-2 mb-0</value>
      <webElementGuid>811adb89-d586-4761-b216-f2ced8ba5989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;umkm_name&quot;)</value>
      <webElementGuid>68eabc14-c3a2-4381-8208-43f3d2d253dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='umkm_name']</value>
      <webElementGuid>431942b3-833f-4bfa-beb8-7e36f8d63e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addDataForm']/input</value>
      <webElementGuid>3693e99e-b23c-4069-a349-203e739cc64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>76f65c6f-cda5-46b2-b476-88cc2b21d2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'umkm_name' and @name = 'umkm_name']</value>
      <webElementGuid>23a2e679-8da1-48fb-918b-208b96b789b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
