<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link Google Maps_gmaps_url</name>
   <tag></tag>
   <elementGuidId>f832b479-a36c-4c4a-80ab-ea39cdbae052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gmaps_url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gmaps_url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Link Google Maps&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53f732a9-8986-49a5-85c8-8b801f525a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6886bc4-7362-42a3-b621-9b8962b1d3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gmaps_url</value>
      <webElementGuid>0209ec59-7d24-4b6b-a1af-72bf4e94b765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gmaps_url</value>
      <webElementGuid>301decd7-5e0d-4f6e-abfc-0f4bf969bef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input px-2 py-2 mb-0</value>
      <webElementGuid>cb530c34-c74c-4d2a-8b66-3e35be3fd102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gmaps_url&quot;)</value>
      <webElementGuid>ef543a9f-a1e4-438d-9ad7-2fb7fe62903c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gmaps_url']</value>
      <webElementGuid>8dbbe90f-b298-470a-9c2c-3f6d9a9153fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addDataForm']/input[5]</value>
      <webElementGuid>faf22b74-2de2-4423-81f1-cb23d5382481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>966162b0-2724-43d2-b753-2679fce7ca61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'gmaps_url' and @name = 'gmaps_url']</value>
      <webElementGuid>4080b998-26b8-43b8-990e-8068fb9ae491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
