<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link Instagram_instagram_url</name>
   <tag></tag>
   <elementGuidId>b43df974-17ee-4e90-97c8-18b3cb48658b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#instagram_url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='instagram_url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Link Instagram&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa7314cf-902c-4350-bce5-450a065724ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c699809f-68a6-417e-9f7b-a459e5aa0f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>instagram_url</value>
      <webElementGuid>3ca515dd-d22c-4338-9c87-21f7eefa4cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instagram_url</value>
      <webElementGuid>51c44b98-32bc-40f8-8512-d0425923f993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input px-2 py-2 mb-0</value>
      <webElementGuid>e7c18408-9548-4269-9faf-b7e3370b40b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;instagram_url&quot;)</value>
      <webElementGuid>5dbb8f65-dbd7-45fd-9491-721f45c56d6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='instagram_url']</value>
      <webElementGuid>3e017c1b-180d-4829-9406-a6548c789623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addDataForm']/input[3]</value>
      <webElementGuid>51cde264-4685-467d-8787-ca49ac65b715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>98ca091f-00f9-4250-be88-1b465473f3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'instagram_url' and @name = 'instagram_url']</value>
      <webElementGuid>5a739fd0-94ab-4c67-ad16-ce5fc5649250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
