<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pemilik UMKM_umkm_owner</name>
   <tag></tag>
   <elementGuidId>297c1ce6-5c6e-4716-b923-0817ebbed2c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#umkm_owner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='umkm_owner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Pemilik UMKM&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9ca3a6b-0f89-4046-9513-0acc5102aea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c9104f2-aa28-4b3f-be0c-8cbafe1880c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>umkm_owner</value>
      <webElementGuid>5f580271-c81f-4cb3-bf7c-aceb0da6b463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>umkm_owner</value>
      <webElementGuid>0be0aeb9-0cbb-4e16-a8a3-4d0e27504f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input px-2 py-2 mb-0</value>
      <webElementGuid>58bece42-d8d4-4207-9329-00a31976ab8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;umkm_owner&quot;)</value>
      <webElementGuid>550f7ab0-5037-4ea2-90c1-b934f866c479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='umkm_owner']</value>
      <webElementGuid>fc92a288-53b9-4265-990e-e83a105994f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addDataForm']/input[2]</value>
      <webElementGuid>2c7338a9-3d97-4bb2-95a7-869ca0d037c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>19b39069-6f31-430c-9c53-1b7b3969f785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'umkm_owner' and @name = 'umkm_owner']</value>
      <webElementGuid>6373f33d-435e-493a-b19e-df6974e074ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
