<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nama UMKM harus terdiri dari 2-25 karakter</name>
   <tag></tag>
   <elementGuidId>67aa89f6-e54a-4499-af5f-8f34c7a74f02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#umkmNameError</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='umkmNameError']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Nama UMKM harus terdiri dari 2-25 karakter.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66b31e9b-5dc6-46cd-9ec3-fa9c053984b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>umkmNameError</value>
      <webElementGuid>9fd647cf-50db-4f9a-ae90-1b7e59327afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>836bd225-1b75-4702-aa22-a5ba9658466a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama UMKM harus terdiri dari 2-25 karakter.</value>
      <webElementGuid>7407a71b-5f16-493c-a8aa-39b78631214f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;umkmNameError&quot;)</value>
      <webElementGuid>aad4d1cd-4b2b-483a-9b8e-7d08f0112a48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='umkmNameError']</value>
      <webElementGuid>c8f8424a-b9e9-4b0a-90fd-dbab3cbee7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addDataForm']/span</value>
      <webElementGuid>767c0a1f-f57b-4646-a192-a71e1f0a6261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama UMKM'])[2]/following::span[1]</value>
      <webElementGuid>86d76298-71ff-4cc1-976b-0ea956c37d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Data UMKM'])[1]/following::span[1]</value>
      <webElementGuid>d4620b3d-21db-4c5b-88f4-ca36537551da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemilik UMKM'])[1]/preceding::span[1]</value>
      <webElementGuid>05987acf-764b-4ad5-817c-9295622aec34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Pemilik harus terdiri dari 2-35 karakter.'])[1]/preceding::span[1]</value>
      <webElementGuid>d5e26cfb-4997-4c99-b571-77b74f9f3a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama UMKM harus terdiri dari 2-25 karakter.']/parent::*</value>
      <webElementGuid>a9c59e37-bca5-4b36-8d19-cdec968e45a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span</value>
      <webElementGuid>baa6404f-9e93-482a-8657-63a0a2bf2bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'umkmNameError' and (text() = 'Nama UMKM harus terdiri dari 2-25 karakter.' or . = 'Nama UMKM harus terdiri dari 2-25 karakter.')]</value>
      <webElementGuid>47b1d342-8772-4858-91cd-d35ae4db3db2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
