<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nama Pemilik harus terdiri dari 2-35 karakter</name>
   <tag></tag>
   <elementGuidId>1ac31067-e02f-4894-afc8-5ea4bf08c5ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#umkmOwnerError</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='umkmOwnerError']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Nama Pemilik harus terdiri dari 2-35 karakter.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fbaf437c-ca0b-4f93-86a6-a610553b9ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>umkmOwnerError</value>
      <webElementGuid>3fe33887-ffdd-4da0-bdae-aa6b2549e380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>e1faf045-30cd-4052-9d48-ffa626d032d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama Pemilik harus terdiri dari 2-35 karakter.</value>
      <webElementGuid>5a2ad16f-6f5c-4850-99ac-944172ebe697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;umkmOwnerError&quot;)</value>
      <webElementGuid>e71b57d4-abaf-46aa-ba4f-2217cc8ac43b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='umkmOwnerError']</value>
      <webElementGuid>16c81144-b490-490f-87e8-85e3485a810d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addDataForm']/span[2]</value>
      <webElementGuid>678495f0-3d84-4c1f-927c-caeea01469ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemilik UMKM'])[1]/following::span[1]</value>
      <webElementGuid>042d1582-59ed-4f53-abba-8facb9b3dbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama UMKM harus terdiri dari 2-25 karakter.'])[1]/following::span[1]</value>
      <webElementGuid>f25fdda7-4cd3-4d63-a9b3-0f4f080eb675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Instagram'])[1]/preceding::span[1]</value>
      <webElementGuid>af9a1bd2-b547-43f2-bfa4-4c227fdabd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Instagram harus terdiri dari 25-50 karakter.'])[1]/preceding::span[1]</value>
      <webElementGuid>799b06ec-fd1f-4703-a64e-b605f900b298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama Pemilik harus terdiri dari 2-35 karakter.']/parent::*</value>
      <webElementGuid>d9c1facc-258a-4114-b0b9-0ffede52d78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>400ed192-3848-4f87-8ad3-8dce95fdff7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'umkmOwnerError' and (text() = 'Nama Pemilik harus terdiri dari 2-35 karakter.' or . = 'Nama Pemilik harus terdiri dari 2-35 karakter.')]</value>
      <webElementGuid>c67fda1c-1855-4c9e-8d96-b55632b7025e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
