<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Link Google Maps harus terdiri dari 25-255 karakter</name>
   <tag></tag>
   <elementGuidId>64e38735-8be7-460f-8f54-f831dbdf33fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gmapsUrlError</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gmapsUrlError']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Link Google Maps harus terdiri dari 25-255 karakter.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4dc2fe5c-699e-4396-b8c2-9e08ba214815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gmapsUrlError</value>
      <webElementGuid>624772fc-af68-4d68-856f-197a434b8b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>83cd4a4d-9ce8-4757-a2a4-018c5d1de85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link Google Maps harus terdiri dari 25-255 karakter.</value>
      <webElementGuid>0cb87662-b3b3-4df6-be48-22963876f6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gmapsUrlError&quot;)</value>
      <webElementGuid>d5c02dc3-b1fa-476e-9b07-1cb9e04060d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gmapsUrlError']</value>
      <webElementGuid>b8f1e173-84d8-42f6-ba08-c7a73d7d98f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addDataForm']/span[5]</value>
      <webElementGuid>0111d4a9-ab27-47cc-bea1-234c59a42828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Google Maps'])[2]/following::span[1]</value>
      <webElementGuid>90209210-ea92-4744-9c01-b2100ae7bd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor WhatsApp harus terdiri dari 12 angka.'])[1]/following::span[1]</value>
      <webElementGuid>6ac12197-4af3-4508-8861-721c1fa546aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latitude'])[1]/preceding::span[1]</value>
      <webElementGuid>3b349506-7063-40e2-a4aa-4b11db7c0675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Longitude'])[1]/preceding::span[2]</value>
      <webElementGuid>4681541c-9f93-4a57-a647-156b7d657325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link Google Maps harus terdiri dari 25-255 karakter.']/parent::*</value>
      <webElementGuid>d548b447-8f92-4045-99c0-2521342773c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]</value>
      <webElementGuid>420ceabc-417d-4ab9-bad3-7bc2e3547bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gmapsUrlError' and (text() = 'Link Google Maps harus terdiri dari 25-255 karakter.' or . = 'Link Google Maps harus terdiri dari 25-255 karakter.')]</value>
      <webElementGuid>8a8d9e62-eb47-4572-92f5-dd088a7653d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
