<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nomor WhatsApp harus terdiri dari 12 angka</name>
   <tag></tag>
   <elementGuidId>1a1344b6-6b88-4332-a6ae-5ca1c258aa0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#whatsappNumberError</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='whatsappNumberError']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Nomor WhatsApp harus terdiri dari 12 angka.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d84d1cb4-c0ff-4077-b6a8-3268191ac63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>whatsappNumberError</value>
      <webElementGuid>a599b909-54de-4c82-be9c-c905a1c1790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>384d3e2b-5ba3-43e2-bef7-baaf9d2f7a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor WhatsApp harus terdiri dari 12 angka.</value>
      <webElementGuid>83d0cfe3-4f48-414d-b9f3-7c3e1a14a12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;whatsappNumberError&quot;)</value>
      <webElementGuid>ccd67b9d-1b4c-4ff2-94a0-de36dc383798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='whatsappNumberError']</value>
      <webElementGuid>15055dab-fe1c-4287-8dd4-92618f490fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addDataForm']/span[4]</value>
      <webElementGuid>eba27705-7402-4fb8-b789-6b99c99874f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cukup masukkan nomor hp saja'])[1]/following::span[1]</value>
      <webElementGuid>1df9639a-5a89-4af1-b23c-e00affcaa324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whatsapp'])[2]/following::span[1]</value>
      <webElementGuid>6051ebde-a1a4-4d40-af61-e72d2aad4999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Google Maps'])[2]/preceding::span[1]</value>
      <webElementGuid>f641d17d-1398-4a07-9229-1c400e5d5cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Google Maps harus terdiri dari 25-255 karakter.'])[1]/preceding::span[1]</value>
      <webElementGuid>05d0dc1d-c77e-48ea-acd1-c248c7f3e8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nomor WhatsApp harus terdiri dari 12 angka.']/parent::*</value>
      <webElementGuid>1cbd0272-6bfb-4d77-8ed1-4d7df8b7a2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]</value>
      <webElementGuid>99e718ae-432a-4e05-a43b-e15eac28c872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'whatsappNumberError' and (text() = 'Nomor WhatsApp harus terdiri dari 12 angka.' or . = 'Nomor WhatsApp harus terdiri dari 12 angka.')]</value>
      <webElementGuid>07c03158-6d75-41fe-bff7-0d51ba1c9805</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
