<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Link Instagram harus terdiri dari 25-50 karakter</name>
   <tag></tag>
   <elementGuidId>343da612-d340-47ce-95d5-5f04f75c3ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#instagramUrlError</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='instagramUrlError']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Link Instagram harus terdiri dari 25-50 karakter.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ff685ae-3426-49a8-abb4-803cb205cb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>instagramUrlError</value>
      <webElementGuid>53e8eac6-8893-4144-b4c1-3d216db2b5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>3a1fe0cf-902f-47f7-8926-1dfb792bafae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link Instagram harus terdiri dari 25-50 karakter.</value>
      <webElementGuid>53626327-9e4c-46f3-b833-e261f79e6819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;instagramUrlError&quot;)</value>
      <webElementGuid>37908310-3eaa-4a15-a22d-f325b176bc23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='instagramUrlError']</value>
      <webElementGuid>2f7f2182-7f87-486e-b464-acf47d886357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addDataForm']/span[3]</value>
      <webElementGuid>f92b6b5a-c73e-4551-a889-fb975af102a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Instagram'])[1]/following::span[1]</value>
      <webElementGuid>5a9cc586-a685-4c83-980f-d9b98be37538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Pemilik harus terdiri dari 2-35 karakter.'])[1]/following::span[1]</value>
      <webElementGuid>dbaed2cd-bddc-45a2-883e-144d567acaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whatsapp'])[2]/preceding::span[1]</value>
      <webElementGuid>0c90c11d-4556-4758-bbc4-d6a78c6a7326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cukup masukkan nomor hp saja'])[1]/preceding::span[1]</value>
      <webElementGuid>fc56c8ff-7118-4491-984a-c239c2431018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link Instagram harus terdiri dari 25-50 karakter.']/parent::*</value>
      <webElementGuid>0b0093a4-ec12-4a40-9a40-1fbdcaee4ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>0c04d89a-99dc-4643-8525-ba693bd7e118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'instagramUrlError' and (text() = 'Link Instagram harus terdiri dari 25-50 karakter.' or . = 'Link Instagram harus terdiri dari 25-50 karakter.')]</value>
      <webElementGuid>8a89cfc0-ad5b-48c0-b798-a74b2f13e28a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
