<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_NIP tidak valid. Silakan gunakan NIP yang terdaftar</name>
   <tag></tag>
   <elementGuidId>0d33509b-3f6f-4518-a768-8a6e49d54f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//small[@id='nipError']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nipError</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;NIP tidak valid. Silakan gunakan NIP yang terdaftar.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>1e90ddb4-57b5-4e13-96f8-05ddb7de2a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nipError</value>
      <webElementGuid>fb1d97e6-81af-44f9-b172-0e2e684c4559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>c8132500-8185-4e26-87ce-bebbcf788c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NIP tidak valid. Silakan gunakan NIP yang terdaftar.</value>
      <webElementGuid>6395b1d3-c860-4756-b371-3e78ab3e4841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nipError&quot;)</value>
      <webElementGuid>1eb37680-138b-4f4e-b5a0-e41c4ec78d1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='nipError']</value>
      <webElementGuid>3faef31c-cf62-4356-8fae-3a6832765624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div/small</value>
      <webElementGuid>7205ce8e-944d-4dcb-937f-a45b70c66e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIP'])[1]/following::small[1]</value>
      <webElementGuid>98461e1e-caac-4ffa-9fc7-a9c6593f02b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::small[1]</value>
      <webElementGuid>25c3f1b1-99be-42af-9863-1ba3f0c3ec28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::small[1]</value>
      <webElementGuid>65693882-6709-4bd8-822a-773c56adcb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::small[1]</value>
      <webElementGuid>c48708d5-4db6-445a-8c0a-4ac639867a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NIP tidak valid. Silakan gunakan NIP yang terdaftar.']/parent::*</value>
      <webElementGuid>e01c7956-622e-48fb-925e-e8b303bc21df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//small</value>
      <webElementGuid>4e68d454-8a33-4f8e-bcb7-84af47c54711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'nipError' and (text() = 'NIP tidak valid. Silakan gunakan NIP yang terdaftar.' or . = 'NIP tidak valid. Silakan gunakan NIP yang terdaftar.')]</value>
      <webElementGuid>13d5f628-d20c-45b4-9546-92798fc7f766</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
