<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Password harus terdiri dari maksimal 20 karakter</name>
   <tag></tag>
   <elementGuidId>9046bf6f-89b4-42b8-9197-b88935d90563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//small[@id='confirmPasswordError']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmPasswordError</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Password harus terdiri dari maksimal 20 karakter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>2877d268-538b-42fe-a338-9108ea4979e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmPasswordError</value>
      <webElementGuid>76a10947-3489-46d0-b61b-d03a64fd7bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>1982c5b0-2fee-4d56-b88d-f383581f0855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password harus terdiri dari maksimal 20 karakter</value>
      <webElementGuid>fc78b757-4871-4e10-ad7a-48375a9debb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmPasswordError&quot;)</value>
      <webElementGuid>0ceb2dcf-c940-47ec-a5d6-09e6c03ed5d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='confirmPasswordError']</value>
      <webElementGuid>122e337f-f8f8-4504-9193-5bef0868f9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[4]/small</value>
      <webElementGuid>7f2c9aeb-0464-41ea-bc35-706310e59e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/following::small[1]</value>
      <webElementGuid>642a13f3-496a-4b0c-9c0e-ac83ad94c475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password tidak boleh lebih dari 20 karakter'])[1]/following::small[1]</value>
      <webElementGuid>a0d85f6c-7c2f-49fa-8c33-ff66751d13bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Password'])[1]/preceding::small[1]</value>
      <webElementGuid>03d5308d-5bbf-40e0-9de9-50f491194d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[2]/preceding::small[1]</value>
      <webElementGuid>959cf08a-4de1-444d-bf18-ebd3ad1050ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password harus terdiri dari maksimal 20 karakter']/parent::*</value>
      <webElementGuid>622da70d-49fd-465a-9bc4-11ecdff40ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/small</value>
      <webElementGuid>aa1d11ee-e648-44b0-80d6-e3f44b021d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'confirmPasswordError' and (text() = 'Password harus terdiri dari maksimal 20 karakter' or . = 'Password harus terdiri dari maksimal 20 karakter')]</value>
      <webElementGuid>282d96f8-3540-4337-a1dd-32325e885c86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
