<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Confirm password tidak boleh kurang d_a23522</name>
   <tag></tag>
   <elementGuidId>82b1e257-4790-4aeb-aa0a-b87f91094f37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//small[@id='confirmPasswordError']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmPasswordError</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Confirm password tidak boleh kurang dari 8 karakter.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>3c8951c6-48fb-44ef-a89a-0cc9fb404cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmPasswordError</value>
      <webElementGuid>95924a08-05c2-48eb-a765-d7c13579bb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>739e7af7-a184-40e8-be39-47fdcbb65c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm password tidak boleh kurang dari 8 karakter.</value>
      <webElementGuid>b6992981-22ba-4a7d-acca-8bd13d183e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmPasswordError&quot;)</value>
      <webElementGuid>c47e4ca3-50ef-42b9-af50-748acf73eca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='confirmPasswordError']</value>
      <webElementGuid>20580ee0-70a0-4a74-be6a-615277b73b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[4]/small</value>
      <webElementGuid>b4436ad5-b8f2-45ff-892e-ccf335b589de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/following::small[1]</value>
      <webElementGuid>3eb538ab-ac9e-48e1-9f54-69785fbffccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::small[2]</value>
      <webElementGuid>ca4621db-7afe-45ea-9f49-4e720c2944b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Password'])[1]/preceding::small[1]</value>
      <webElementGuid>812f3dd1-5c9a-4a08-941d-ec73d8382532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[2]/preceding::small[1]</value>
      <webElementGuid>94ca0f8a-9dec-43da-9953-ee7e5d37df0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm password tidak boleh kurang dari 8 karakter.']/parent::*</value>
      <webElementGuid>dbd8da56-717b-40ca-b91e-e4d15ce8d9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/small</value>
      <webElementGuid>9359c8e8-55b6-472b-908b-c54eb0853edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'confirmPasswordError' and (text() = 'Confirm password tidak boleh kurang dari 8 karakter.' or . = 'Confirm password tidak boleh kurang dari 8 karakter.')]</value>
      <webElementGuid>fecfd1d6-d4d5-4514-8100-79172dc317a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
