<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Confirm password tidak boleh kurang dari 8 karakter</name>
   <tag></tag>
   <elementGuidId>0548037e-1c8e-4698-ace6-a117dad127d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//small[@id='confirmPasswordError']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmPasswordError</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Confirm password tidak boleh kurang dari 8 karakter.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>66a67fc6-73bd-4e95-b046-6e4892eb83b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmPasswordError</value>
      <webElementGuid>9299a163-cfdc-4a95-90b3-4f07f8c15cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>c4813eba-3714-4193-a7b2-88a0f9303436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm password tidak boleh kurang dari 8 karakter.</value>
      <webElementGuid>e456b94f-9ee2-442e-bd0e-d565ebcc3044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmPasswordError&quot;)</value>
      <webElementGuid>ccc76139-16a5-4326-881d-90b43c64ac8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='confirmPasswordError']</value>
      <webElementGuid>9e92f6fc-e751-49dd-8114-6984c55b7940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[4]/small</value>
      <webElementGuid>e452d919-087d-46c5-b56f-27f38edba15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/following::small[1]</value>
      <webElementGuid>436e1711-f9bc-4a6d-a29e-ffb5d80de4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password harus minimal 8 karakter'])[1]/following::small[1]</value>
      <webElementGuid>af908c97-8bea-431c-b945-8b95938a47af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Password'])[1]/preceding::small[1]</value>
      <webElementGuid>73606e66-8e0a-4a3e-bef9-401216082d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[2]/preceding::small[1]</value>
      <webElementGuid>1df3130f-bcc6-4047-bdab-2eb78c39ff03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm password tidak boleh kurang dari 8 karakter.']/parent::*</value>
      <webElementGuid>4042c03a-de2f-47b8-9a65-5cb4036f21e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/small</value>
      <webElementGuid>6c40978a-52a2-4b3a-9126-cf1babb04c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'confirmPasswordError' and (text() = 'Confirm password tidak boleh kurang dari 8 karakter.' or . = 'Confirm password tidak boleh kurang dari 8 karakter.')]</value>
      <webElementGuid>632abd81-1040-4ad6-b1e9-68d14c2e018a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
